AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Find Unused Security Groups
  
  Serverless version of find-unused-sgs for automated security group cleanup analysis

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 8 1 * ? *)"
    Description: CloudWatch Events schedule expression (default monthly on 1st at 8 AM)

  ScanAllRegions:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Scan all AWS regions (default current region only)

  MaxWorkers:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of parallel workers for region scanning

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SCAN_ALL_REGIONS: !Ref ScanAllRegions
        MAX_WORKERS: !Ref MaxWorkers
        SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"

Resources:
  FindUnusedSGsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: find-unused-sgs-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - Find Unused Security Groups"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of unused security groups finder"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeSecurityGroups
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeVpcs
                - ec2:DescribeInstances
                - ec2:DescribeLaunchTemplates
                - ec2:DescribeLaunchTemplateVersions
                - sns:Publish
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  FindUnusedSGsFunction:
    Description: "Find Unused Security Groups Lambda Function ARN"
    Value: !GetAtt FindUnusedSGsFunction.Arn
  FindUnusedSGsFunctionRole:
    Description: "Implicit IAM Role created for Find Unused SGs function"
    Value: !GetAtt FindUnusedSGsFunctionRole.Arn
  SecurityFindingsTopic:
    Description: "Security Findings SNS Topic ARN"
    Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"