version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cleanup-snapshots-stack"
s3_bucket = ""  # Will be created automatically
s3_prefix = "cleanup-snapshots-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
parameter_overrides = "Environment=\"dev\" Schedule=\"cron(0 3 ? * SUN *)\" DaysOld=\"30\" ScanAllRegions=\"true\" DryRun=\"true\" RequireUntagged=\"false\" MaxWorkers=\"10\""
