AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  List RDS Instances Inventory
  
  Serverless version of list-rds-instances for automated RDS inventory

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 5 1 * ? *)"
    Description: CloudWatch Events schedule expression (default monthly on 1st at 5 AM)

  ScanAllRegions:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Scan all AWS regions (default current region only)

  MaxWorkers:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of parallel workers for region scanning

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SCAN_ALL_REGIONS: !Ref ScanAllRegions
        MAX_WORKERS: !Ref MaxWorkers
        SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"

Resources:
  ListRDSInstancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-rds-instances-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - List RDS Instances Inventory"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of RDS instances inventory"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - rds:DescribeDBInstances
                - rds:DescribeDBClusters
                - rds:DescribeDBSubnetGroups
                - rds:DescribeDBParameterGroups
                - rds:DescribeDBClusterParameterGroups
                - rds:ListTagsForResource
                - ec2:DescribeRegions
                - sns:Publish
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  ListRDSInstancesFunction:
    Description: "List RDS Instances Inventory Lambda Function ARN"
    Value: !GetAtt ListRDSInstancesFunction.Arn
  ListRDSInstancesFunctionRole:
    Description: "Implicit IAM Role created for List RDS Instances function"
    Value: !GetAtt ListRDSInstancesFunctionRole.Arn
  SecurityFindingsTopic:
    Description: "Security Findings SNS Topic ARN"
    Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"