AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Check Public S3 Buckets
  
  Serverless version of check-public-s3 for automated S3 security auditing

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 9 ? * MON *)"
    Description: Schedule expression for execution
    
  PublicOnly:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Only report publicly accessible buckets

Globals:
  Function:
    Timeout: 600
    MemorySize: 512
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        PUBLIC_ONLY: !Ref PublicOnly
        SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"

Resources:
  CheckPublicS3Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-public-s3-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - Check Public S3 Buckets"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of public S3 buckets checker"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
                - s3:GetBucketAcl
                - s3:GetBucketPolicy
                - s3:GetBucketPolicyStatus
                - s3:GetPublicAccessBlock
                - s3:GetBucketPublicAccessBlock
                - s3:GetBucketLogging
                - s3:GetBucketVersioning
                - s3:GetEncryptionConfiguration
                - s3:GetBucketWebsite
                - sns:Publish
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  CheckPublicS3Function:
    Description: "Check Public S3 Buckets Lambda Function ARN"
    Value: !GetAtt CheckPublicS3Function.Arn
  CheckPublicS3FunctionRole:
    Description: "Implicit IAM Role created for Check Public S3 function"
    Value: !GetAtt CheckPublicS3FunctionRole.Arn
  SecurityFindingsTopic:
    Description: "Security Findings SNS Topic ARN"
    Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"