AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Cost Monitor Lambda Function
  
  Serverless version of aws-cost-monitor for automated AWS cost monitoring and alerting

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 9 * * ? *)"
    Description: CloudWatch Events schedule expression
  
  DailyThreshold:
    Type: Number
    Default: 100
    Description: Daily spending threshold for alerts
    
  MonthlyThreshold:
    Type: Number
    Default: 3000
    Description: Monthly spending threshold for alerts

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        DAILY_THRESHOLD: !Ref DailyThreshold
        MONTHLY_THRESHOLD: !Ref MonthlyThreshold
        FINOPS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:FinOps"

Resources:
  AwsCostMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-cost-monitor-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of aws-cost-monitor"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ce:GetCostAndUsage
                - ce:GetUsageReport
                - ce:GetDimensionValues
                - ce:GetMetricStat
                - ce:GetRightsizingRecommendation
                - ce:GetSavingsUtilization
                - ce:GetSavingsPlansUtilization
                - ce:ListCostCategoryDefinitions
                - budgets:ViewBudget
                - budgets:DescribeBudgets
                - support:DescribeTrustedAdvisorChecks
                - support:DescribeTrustedAdvisorCheckResult
                - sns:Publish
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  AwsCostMonitorFunction:
    Description: "AWS Cost Monitor Lambda Function ARN"
    Value: !GetAtt AwsCostMonitorFunction.Arn
  AwsCostMonitorFunctionRole:
    Description: "Implicit IAM Role created for AWS Cost Monitor function"
    Value: !GetAtt AwsCostMonitorFunctionRole.Arn
  FinOpsTopic:
    Description: "FinOps Cost Management Alerts SNS Topic ARN"
    Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:FinOps"