AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stop Idle EC2 Instances
  
  Serverless version of stop-idle-ec2 for automated cost optimization

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 20 * * ? *)"
    Description: CloudWatch Events schedule expression (default daily at 8 PM)

  ScanAllRegions:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Scan all AWS regions (default current region only)

  MaxWorkers:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of parallel workers for region scanning

  DryRun:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Dry run mode - preview actions without stopping instances

  CpuThreshold:
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 50
    Description: CPU utilization threshold percentage

  MonitoringHours:
    Type: Number
    Default: 24
    MinValue: 4
    MaxValue: 168
    Description: Hours to monitor CPU usage

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SCAN_ALL_REGIONS: !Ref ScanAllRegions
        MAX_WORKERS: !Ref MaxWorkers
        DRY_RUN: !Ref DryRun
        CPU_THRESHOLD: !Ref CpuThreshold
        MONITORING_HOURS: !Ref MonitoringHours

Resources:
  StopIdleEC2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stop-idle-ec2-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - Stop Idle EC2 Instances"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of idle EC2 instance stopping"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeInstanceTypes
                - ec2:DescribeRegions
                - ec2:DescribeVolumes
                - ec2:DescribeSnapshots
                - ec2:StopInstances
                - cloudwatch:GetMetricStatistics
                - cloudwatch:GetMetricData
                - autoscaling:DescribeAutoScalingGroups
                - autoscaling:DescribeAutoScalingInstances
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  StopIdleEC2Function:
    Description: "Stop Idle EC2 Instances Lambda Function ARN"
    Value: !GetAtt StopIdleEC2Function.Arn
  StopIdleEC2FunctionRole:
    Description: "Implicit IAM Role created for Stop Idle EC2 function"
    Value: !GetAtt StopIdleEC2FunctionRole.Arn