version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "list-lambdas-stack"
s3_bucket = ""  # Will be created automatically
s3_prefix = "list-lambdas-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
parameter_overrides = "Environment=\"dev\" Schedule=\"cron(0 7 1 * ? *)\" ScanAllRegions=\"true\" MaxWorkers=\"10\""
