AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  List Lambda Functions Inventory
  
  Serverless version of list-lambdas for automated Lambda function inventory

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 7 1 * ? *)"
    Description: CloudWatch Events schedule expression (default monthly on 1st at 7 AM)

  ScanAllRegions:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Scan all AWS regions (default current region only)

  MaxWorkers:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of parallel workers for region scanning

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SCAN_ALL_REGIONS: !Ref ScanAllRegions
        MAX_WORKERS: !Ref MaxWorkers

Resources:
  ListLambdasFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-lambdas-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - List Lambda Functions Inventory"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of Lambda functions inventory"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:ListFunctions
                - lambda:GetFunction
                - lambda:ListTags
                - lambda:GetPolicy
                - lambda:ListEventSourceMappings
                - ec2:DescribeRegions
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  ListLambdasFunction:
    Description: "List Lambda Functions Inventory Lambda Function ARN"
    Value: !GetAtt ListLambdasFunction.Arn
  ListLambdasFunctionRole:
    Description: "Implicit IAM Role created for List Lambdas function"
    Value: !GetAtt ListLambdasFunctionRole.Arn