AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ELB/ALB Security Auditor
  
  Serverless version of elb-audit for automated load balancer security auditing

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  Schedule:
    Type: String
    Default: "cron(0 9 * * ? *)"
    Description: CloudWatch Events schedule expression (default daily at 9 AM)

  ScanAllRegions:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Scan all AWS regions (default current region only)

  MaxWorkers:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of parallel workers for region scanning

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SCAN_ALL_REGIONS: !Ref ScanAllRegions
        MAX_WORKERS: !Ref MaxWorkers
        SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"

Resources:
  ELBAuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: elb-audit-lambda
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: !Sub "${Environment} - ELB/ALB Security Auditor"
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Description: "Scheduled execution of ELB/ALB security audit"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:DescribeLoadBalancers
                - elasticloadbalancing:DescribeListeners
                - elasticloadbalancing:DescribeTargetGroups
                - elasticloadbalancing:DescribeTargetHealth
                - elasticloadbalancing:DescribeRules
                - ec2:DescribeRegions
                - sns:Publish
                - sts:GetCallerIdentity
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  ELBAuditFunction:
    Description: "ELB/ALB Security Auditor Lambda Function ARN"
    Value: !GetAtt ELBAuditFunction.Arn
  ELBAuditFunctionRole:
    Description: "Implicit IAM Role created for ELB Audit function"
    Value: !GetAtt ELBAuditFunctionRole.Arn
  SecurityFindingsTopic:
    Description: "Security Findings SNS Topic ARN"
    Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SecurityFindings"